name: 'Update major/minor semver'
description: 'Updates major/minor release tags on a tag push'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  message:
    description: 'Tag message.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'refresh-cw'
  color: 'green'
