name: 'Update major/minor semver'
description: 'Updates major/minor release tags on a tag push'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN. Optional if you use checkout@v2 action.'
    default: '${{ github.token }}'
  tag:
    description: 'Optional. Existing tag to update from. Default comes from $GITHUB_REF.'
    required: false
  message:
    description: 'Tag message.'
    required: false
  major_version_tag_only:
    description: 'Optional. Create only major version tags.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Update major/minor semver tags
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_MAJOR_VERSION_TAG_ONLY: ${{ inputs.major_version_tag_only }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
      run: ${{ github.action_path }}/script.sh
# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'refresh-cw'
  color: 'green'
