name: 'Update major/minor semver'
description: 'Updates major/minor release tags on a tag push'
author: 'haya14busa'
inputs:
  tag:
    description: 'Optional. Existing tag to update from. Default comes from $GITHUB_REF.'
    required: false
  message:
    description: 'Tag message.'
    required: false
  major_version_tag_only:
    description: 'Optional. Create only major version tags.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'refresh-cw'
  color: 'green'
